{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::211125419540:oidc-provider/token.actions.githubusercontent.com"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "token.actions.githubusercontent.com:sub": "repo:aji0110/Github-action-Repo.git/knaws:ref:refs/heads/main"
                }
            }
        }
    ]
}

Github action yaml:

name: Configure AWS Credentials and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Allow the workflow to request OIDC tokens
  contents: read   # Allow the workflow to access the repository contents

jobs:
  configure-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::211125419540:role/Git-action-workflow
          role-session-name: github-actions-session
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the version of Terraform you want to use

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        
#      - name: Terraform Destroy
#       run: terraform destroy -auto-approve        
